sudo: required
services:
  - docker

before_install:
  - docker build -t r3r00t3d/docker-react -f Dockerfile.dev .

script:
  - docker run r3r00t3d/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-085518807864"
  bucket_path: "docker-react"
  on:
    branch: master